export default {
  token: state => state.token,
  is_register: state => state.is_register,
  is_login: state => state.is_login,
  hotel: state => state.hotel,
  query: state => state.query,
  query_keys: state => state.query_keys,
  cities: state => state.cities,
  destinations: state => state.destinations,
  hotel_length: state => state.hotel_length,
  hotel_news: state => state.hotel_news,
  recent: state => state.recent,
  sale: state => state.sale,
  tour: state => state.tour,
  tour_get: state => state.tour_get,
  tour_id: state => state.tour_id,
  step2: state => state.step2,
  help_categories: state => state.help_categories,
  booking_details: state => state.booking_details,
  inf_account: state => state.inf_account,
  help_message: state => state.help_message,
  update_password: state => state.update_password,
  csrf: state => state.csrf,
  tour_all: state => state.tour_all,
  limit: state => state.limit,
  hotel_min: state => state.hotel_min,
  offset: state => state.offset
}
