let getInfoAccount = [
  {
    name: "Месяц",
    disabled: '',
    number: 0,
    selected: true
  },
  {
    name: "Январь",
    number: '01'
  },
  {
    name: "Февраль",
    number: '02'
  },
  {
    name: "Март",
    number: '03'
  },
  {
    name: "Апрель",
    number: '04'
  },
  {
    name: "Май",
    number: '05'
  },
  {
    name: "Июнь",
    number: '06'
  },
  {
    name: "Июль",
    number: '07'
  },
  {
    name: "Август",
    number: '08'
  },
  {
    name: "Сентябрь",
    number: '09'
  },
  {
    name: "Октябрь",
    number: '10'
  },
  {
    name: "Ноябрь",
    number: '11'
  },
  {
    name: "Декабрь",
    number: '12'
  },
]
let getInfoIssuer = [
  {
    name: "Список",
    disabled: '',
    selected: true
  },
  {name: "Afghanistan"},
  {name: "Albania"},
  {name: "Algeria"},
  {name: "Andorra"},
  {name: "Angola"},
  {name: "Anguilla"},
  {name: "Antarctica"},
  {name: "Antigua and Barbuda"},
  {name: "Argentina"},
  {name: "Armenia"},
  {name: "Aruba"},
  {name: "Australia"},
  {name: "Austria"},
  {name: "Azerbaijan"},
  {name: "Bahamas"},
  {name: "Bahrain"},
  {name: "Bangladesh"},
  {name: "Barbados"},
  {name: "Belarus"},
  {name: "Belgium"},
  {name: "Belize"},
  {name: "Benin"},
  {name: "Bermuda"},
  {name: "Bhutan"},
  {name: "Bolivia"},
  {name: "Bosnia and Herzegovina"},
  {name: "Botswana"},
  {name: "Brazil"},
  {name: "British Virgin Islands"},
  {name: "Brunei"},
  {name: "Bulgaria"},
  {name: "Burkina Faso"},
  {name: "Burma"},
  {name: "Burundi"},
  {name: "Buthan"},
  {name: "Cambodia"},
  {name: "Cameroon"},
  {name: "Canada"},
  {name: "Cape Verde"},
  {name: "Cayman Island"},
  {name: "Central African Republic"},
  {name: "Chad"},
  {name: "Chile"},
  {name: "China"},
  {name: "Colombia"},
  {name: "Comoros"},
  {name: "Cook Islands"},
  {name: "Costa Rica"},
  {name: "Croatia"},
  {name: "Cuba"},
  {name: "Cyprus"},
  {name: "Czech Republic"},
  {name: "Democratic Republic of the Congo"},
  {name: "Denmark"},
  {name: "Djibouti"},
  {name: "Dominica"},
  {name: "Dominican Republic"},
  {name: "Dutch Antilles"},
  {name: "East Timor"},
  {name: "Ecuador"},
  {name: "Egypt"},
  {name: "Equatorial Guinea"},
  {name: "Eritrea"},
  {name: "Estonia"},
  {name: "Ethiopia"},
  {name: "Faroe Islands"},
  {name: "Fiji"},
  {name: "Finland"},
  {name: "France"},
  {name: "French Polynesia"},
  {name: "Gabon"},
  {name: "Gambia"},
  {name: "Georgia"},
  {name: "Germany"},
  {name: "Ghana"},
  {name: "Gibraltar"},
  {name: "Greece"},
  {name: "Greenland"},
  {name: "Grenada"},
  {name: "Guatemala"},
  {name: "Guinea"},
  {name: "Guinea-Bissau"},
  {name: "Guyana"},
  {name: "Haiti"},
  {name: "Honduras"},
  {name: "Hungary"},
  {name: "Iceland"},
  {name: "India"},
  {name: "Indonesia"},
  {name: "Iran"},
  {name: "Iraq"},
  {name: "Ireland"},
  {name: "Israel"},
  {name: "Italy"},
  {name: "Ivory Coast"},
  {name: "Jamaica"},
  {name: "Japan"},
  {name: "Jersey"},
  {name: "Jordan"},
  {name: "Kazakhstan"},
  {name: "Kenya"},
  {name: "Kiribati"},
  {name: "Kosovo"},
  {name: "Kuwait"},
  {name: "Kyrgyzstan"},
  {name: "Laos"},
  {name: "Latvia"},
  {name: "Lebanon"},
  {name: "Lesotho"},
  {name: "Liberia"},
  {name: "Libya"},
  {name: "Liechtenstein"},
  {name: "Lithuania"},
  {name: "Luxembourg"},
  {name: "Macau"},
  {name: "Macedonia"},
  {name: "Madagascar"},
  {name: "Malawi"},
  {name: "Malaysia"},
  {name: "Maldives"},
  {name: "Mali"},
  {name: "Malta"},
  {name: "Marshall Islands"},
  {name: "Mauritania"},
  {name: "Mauritius"},
  {name: "Mexico"},
  {name: "Micronesia"},
  {name: "Moldova"},
  {name: "Monaco"},
  {name: "Mongolia"},
  {name: "Montenegro"},
  {name: "Montserrat"},
  {name: "Morocco"},
  {name: "Mozambique"},
  {name: "Myanmar"},
  {name: "Namibia"},
  {name: "Nauru"},
  {name: "Nepal"},
  {name: "Netherlands"},
  {name: "Netherlands Antilles"},
  {name: "New Zealand"},
  {name: "Nicaragua"},
  {name: "Niger"},
  {name: "Nigeria"},
  {name: "Niue"},
  {name: "North Korea"},
  {name: "Norway"},
  {name: "Oman"},
  {name: "One day"},
  {name: "Pakistan"},
  {name: "Palau"},
  {name: "Panama"},
  {name: "Papua New Guinea"},
  {name: "Paraguay"},
  {name: "Peru"},
  {name: "Philippines"},
  {name: "Poland"},
  {name: "Portugal"},
  {name: "Puerto Rico"},
  {name: "Qatar"},
  {name: "Romania"},
  {name: "Russia"},
  {name: "Rwanda"},
  {name: "Saint Martin"},
  {name: "Salvador"},
  {name: "Samoa"},
  {name: "Sao Tome &amp; Principe"},
  {name: "Saudi Arabia"},
  {name: "Senegal"},
  {name: "Serbia"},
  {name: "Seychelles"},
  {name: "Sierra Leone"},
  {name: "Singapore"},
  {name: "Slovakia"},
  {name: "Slovenia"},
  {name: "Solomon Islands"},
  {name: "Somalia"},
  {name: "South Africa"},
  {name: "South Korea"},
  {name: "Spain"},
  {name: "Sri Lanka"},
  {name: "St Kitts &amp; Nevis"},
  {name: "St Lucia"},
  {name: "St Vincent &amp; the Grenadines"},
  {name: "Sudan"},
  {name: "Suriname"},
  {name: "Swaziland"},
  {name: "Sweden"},
  {name: "Switzerland"},
  {name: "Syria"},
  {name: "Tajikistan"},
  {name: "Tanzania"},
  {name: "Taïwan"},
  {name: "Territoires Palestiniens"},
  {name: "Thailand"},
  {name: "Togo"},
  {name: "Tonga"},
  {name: "Trinidad &amp; Tobago"},
  {name: "Tunisia"},
  {name: "Turkey"},
  {name: "Turkmenistan"},
  {name: "Tuvalu"},
  {name: "Uganda"},
  {name: "Ukraine"},
  {name: "United Arab Emirates"},
  {name: "United Kingdom"},
  {name: "United States"},
  {name: "Uruguay"},
  {name: "Uzbekistan"},
  {name: "Vanuatu"},
  {name: "Vatican City"},
  {name: "Venezuela"},
  {name: "Vietnam"},
  {name: "Yemen"},
  {name: "Zambia"},
  {name: "Zimbabwe"},
]
let getInfoMonth = [
  {
    name: "Месяц",
    disabled: '',
    selected: true
  },
  {name: "January", number: 1},
  {name: "February", number: 2},
  {name: "March", number: 3},
  {name: "April", number: 4},
  {name: "May", number: 5},
  {name: "June", number: 6},
  {name: "July", number: 7},
  {name: "August", number: 8},
  {name: "September", number: 9},
  {name: "October", number: 10},
  {name: "November", number: 11},
  {name: "December", number: 12},

]
export default {getInfoAccount, getInfoIssuer, getInfoMonth};
